baseURL = "https://tsuzukihashi.github.io"
languageCode = "en-us"
title = "愚直プログラマ"
theme = "m10c"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
[params]
  author = "Ryo Tsuzukihashi"
  description = "Yahoo! JAPAN iOS Engineer."
  avatar = "images/profile.jpg"
  menu_item_separator = " - "
  [[params.social]]
    name = "github"
    url = "https://github.com/tsuzukihashi"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/tsuzuki817"
  [[params.social]]
    name = "facebook"
    url = "https://www.facebook.com/tsuzukihashi/"
  [[params.social]]
    name = "instagram"
    url = "https://www.instagram.com/tsuzuki817"
  [[params.social]]
    name = "qiita"
    url = "https://qiita.com/tsuzuki817"
[params.style]
  darkestColor = "#d35050"
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#fff"

